SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[RollingpeopleVaccinated]
  FROM [sqltrainingcorona].[dbo].[percentpopulationVaccinated]
